### ISSUE TITLE
How to get the url of FB's post?

### ISSUE THREAD

**Issue by dennisat** [justinmahar/react-social-media-embed#14]
This is not a bug or issue report... but seems to be the only one that can answer.

For instance, load this address https://www.facebook.com/9gag/posts/pfbid024mcPB6f5Q5DWh1XZUkShUznrVFrkpzRfy1krtCA4H5sJQ67Bd4vjWRnqkkRG1U8tl
This is a Post address... a sort off. This address cannot be used as `url` for you component.

**What's the proper way to get a link of a Facebook post to be used in `react-social-media-embed`?**

**Comment by dennisat** [comment]
is anybody out there...

**Comment by dennisat** [comment]
@justinmahar is this project deprecated?

**Comment by justinmahar** [comment]
@dennisat Select the ellipsis button next to the post and choose Embed.

<img width="702" alt="1" src="https://user-images.githubusercontent.com/3472836/199075047-cdb5e6c2-dfff-417d-baba-fd460a5f359f.png">

Then, click "Advanced settings"

<img width="549" alt="2" src="https://user-images.githubusercontent.com/3472836/199075192-4145da6e-5087-4624-b862-6656b0db7277.png">

That will bring you to a page that allows you to generate code for the post. Within that code, you can find the link.

<img width="453" alt="3" src="https://user-images.githubusercontent.com/3472836/199075385-0331fe81-100d-43e5-8d3c-f0d58a37fc8c.png">

<img width="711" alt="4" src="https://user-images.githubusercontent.com/3472836/199075739-2f0eac67-5f83-4b0b-8059-2d350c92b152.png">

So for the post you mentioned, the link would be `https://www.facebook.com/9gag/posts/10162296746226840`. I just tried this link with the [demo](https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-facebookembed--main-example) and it works.

I'll have to add these instructions to the docs since Facebook has this buried. Thanks for opening the issue!

**Comment by justinmahar** [comment]
Added to docs:
https://justinmahar.github.io/react-social-media-embed/?path=/story/home--page#how-do-you-get-a-facebook-post-url

**Comment by dennisat** [comment]
Thanks @justinmahar it works

**Comment by Jenietoc** [comment]
Hello Guys, this is still working?
