### ISSUE TITLE
Instagram example do not work - demo page

### ISSUE THREAD

**Issue by offminded** [justinmahar/react-social-media-embed#80]
Instagram example is not working. Please check the demo page:
https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-instagramembed--main-example

**Comment by matheusdamiao** [comment]
It seems Instagram Embed is not working in many places. 
I've just tried without this library in a Nextjs project and I got the same error that I found here in the demo page:

`Cross-Origin Read Blocking (CORB) blocked a cross-origin response.`

Just inspect the `embed.js` script in the network tab that you'll find this `302 found` response

**Comment by matheusdamiao** [comment]
@justinmahar any updates on this issue?

**Comment by matheusdamiao** [comment]
I seriously don't know what happened, but everything is working now, even the demo instagram section.
@offminded check and close the issue

**Comment by GabrielNogueiraBR** [comment]
I went through the same scenario as well. In my application, the Instagram embed stopped working, returning a 302 status code on the request for the embed.js file and it would stay in infinite loading.

The same thing happened on the Demo page, so it was probably a global issue that affected the entire Instagram embed functionality, because now everything is back to normal for me too.

**Comment by offminded** [comment]
Ok back to normal for me too, seems it was a global issue. Thanks for the input @matheusdamiao @GabrielNogueiraBR. Closing.
